#%RAML 1.0 NamedExample
value: |
  {
    "productId": "123456",
    "variantId": "234567",
    "warehouses": [
      {
        "warehouseId": "124",
        "name": "Central Warehouse ",
        "availableCount": 1000,  
        "lastUpdated": "2017-07-21T12:00:00.000Z"
      }
    ]
  }